(() => {
"use strict";

const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const rad=d=>d*Math.PI/180;
const canvas=$("canvas");
const ctx=canvas.getContext("2d");

let W=0,H=0,DPR=1,baseScale=1,cx=0,cy=0;
let viewX=0,viewY=0,viewZoom=1;
let selected=-1,mode="edit",snakeScale=1,perspectiveStrength=1,currentCrossing=0;
let showPoints=true,showLabels=true,showArrows=true,showXray=true,showNumbers=true,showTransitions=true,showContacts=true;
let diagnosticMode=true,cleanMode=false,spaceHeld=false;

const display={outline:true,outlineThickness:.08,referenceCircle:false,mouthTailGuide:false,closurePreview:false,gazeArrow:true,gazeOpacity:.95,gazeStars:true};
const endpoint={headSize:1,headRotation:0,neckWidth:1,eyeOpen:.35,eyeX:.22,eyeY:-.18,gazeDirection:-70,mouthOpen:.18,tailLength:1,tailWidth:1,tailDirection:0,tailCurvature:0};
const earth={x:0,y:0,r:2.50,depth:6.5,scale:1,alpha:1,locked:true};
const moon={visible:true,angle:35,radius:3,size:.27,relativeDepth:1};
const lighting={enabled:true,direction:-45,intensity:.65,softness:.6,shadows:true,depthFog:.16};
let crossingOverrides={};
const checkpoints={};
const history={undo:[],redo:[],limit:50};

const oldClosedPose=[[-.55,2.35,.8],[-1.45,2.18,.4],[-2.35,1.60,0],[-2.85,.65,-.3],[-2.90,-.55,.3],[-2.35,-1.65,1.5],[-1.25,-2.35,3.2],[.05,-2.58,4.2],[1.35,-2.30,3.3],[2.35,-1.55,1.5],[2.82,-.45,0],[2.70,.75,-1],[2.15,1.65,-2.2],[1.20,2.20,-2.8],[-.30,2.37,-1.5]];
const migrateDepth=z=>clamp((+z||0)+6.5,0,14);
const makePoint=p=>({x:+p[0],y:+p[1],z:migrateDepth(p[2]),width:1,earth:"AUTO",contact:"AUTO"});
const closedPose=oldClosedPose.map(makePoint);
let pts=closedPose.map(p=>({...p}));
let biteTail=true,preserveLength=false,preserveTarget=null;
let sparkleFrame=0,sparkleTimer=0;

function clone(v){return JSON.parse(JSON.stringify(v));}
function sceneState(){return{pts:clone(pts),selected,snakeScale,perspectiveStrength,endpoint:clone(endpoint),earth:clone(earth),moon:clone(moon),lighting:clone(lighting),crossingOverrides:clone(crossingOverrides),display:clone(display),constraints:{biteTail,preserveLength,preserveTarget},flags:{showPoints,showLabels,showArrows,showXray,showNumbers,showTransitions,showContacts,diagnosticMode,cleanMode}};}
function sameScene(a,b){return JSON.stringify(a)===JSON.stringify(b);}
function applyScene(s){pts=clone(s.pts||pts);selected=Number.isInteger(s.selected)?clamp(s.selected,-1,pts.length-1):-1;snakeScale=+(s.snakeScale??1);perspectiveStrength=+(s.perspectiveStrength??1);Object.assign(endpoint,s.endpoint||{});Object.assign(earth,s.earth||{});Object.assign(moon,s.moon||{});Object.assign(lighting,s.lighting||{});crossingOverrides=clone(s.crossingOverrides||{});Object.assign(display,s.display||{});if(s.constraints){biteTail=s.constraints.biteTail??biteTail;preserveLength=s.constraints.preserveLength??preserveLength;preserveTarget=Number.isFinite(+s.constraints.preserveTarget)?+s.constraints.preserveTarget:null;}if(preserveLength&&!Number.isFinite(preserveTarget))preserveTarget=arcLength();if(s.flags){showPoints=s.flags.showPoints??showPoints;showLabels=s.flags.showLabels??showLabels;showArrows=s.flags.showArrows??showArrows;showXray=s.flags.showXray??showXray;showNumbers=s.flags.showNumbers??showNumbers;showTransitions=s.flags.showTransitions??showTransitions;showContacts=s.flags.showContacts??showContacts;diagnosticMode=s.flags.diagnosticMode??diagnosticMode;cleanMode=s.flags.cleanMode??cleanMode;}syncAllUI();draw();autosave();syncSparkleAnimation();}
function commit(before){const after=sceneState();if(before&&!sameScene(before,after)){history.undo.push(before);if(history.undo.length>history.limit)history.undo.shift();history.redo.length=0;syncHistory();autosave();}}
function mutate(fn){const before=sceneState();fn();commit(before);syncAllUI();draw();syncSparkleAnimation();}
function undo(){if(!history.undo.length)return;const cur=sceneState(),prev=history.undo.pop();history.redo.push(cur);applyScene(prev);syncHistory();}
function redo(){if(!history.redo.length)return;const cur=sceneState(),next=history.redo.pop();history.undo.push(cur);applyScene(next);syncHistory();}
function syncHistory(){$("undoBtn").disabled=!history.undo.length;$("redoBtn").disabled=!history.redo.length;}

let autosaveTimer=0;
function autosave(){try{localStorage.setItem("ouroborosPoseEditor.autosave.v9",JSON.stringify(exportState(true)));localStorage.setItem("ouroborosPoseEditor.schema","9");}catch(e){}}
function scheduleAutosave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(autosave,220);}
function restoreAutosave(){try{const raw=localStorage.getItem("ouroborosPoseEditor.autosave.v9")||localStorage.getItem("ouroborosPoseEditor.autosave.v8")||localStorage.getItem("ouroborosPoseEditor.autosave.v7");if(raw)importData(JSON.parse(raw),true);}catch(e){}}

function currentScale(){return baseScale*viewZoom;}
function depthScale(z){return Math.exp((z-6.5)*.095*perspectiveStrength);}
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0);baseScale=Math.min(W,H)*.105;cx=W*.5;cy=H*.51;draw();}
function project(p){const s=currentScale();return{x:cx+viewX+p.x*s,y:cy+viewY-p.y*s,z:p.z};}
function screenToWorld(x,y){const s=currentScale();return{x:(x-cx-viewX)/s,y:-(y-cy-viewY)/s};}
function zoomAt(x,y,nextZoom){const old=viewZoom;nextZoom=clamp(nextZoom,.35,4);if(Math.abs(nextZoom-old)<1e-8)return;const wx=(x-cx-viewX)/(baseScale*old),wy=-(y-cy-viewY)/(baseScale*old);viewZoom=nextZoom;viewX=x-cx-wx*baseScale*viewZoom;viewY=y-cy+wy*baseScale*viewZoom;syncViewportUI();draw();scheduleAutosave();}

function catmull(a,b,c,d,t,key){const t2=t*t,t3=t2*t;return .5*(2*b[key]+(-a[key]+c[key])*t+(2*a[key]-5*b[key]+4*c[key]-d[key])*t2+(-a[key]+3*b[key]-3*c[key]+d[key])*t3);}
function curvePointAtSource(source){source=clamp(source,0,pts.length-1);const i=Math.min(pts.length-2,Math.floor(source)),t=source-i,a=pts[Math.max(0,i-1)],b=pts[i],c=pts[i+1],d=pts[Math.min(pts.length-1,i+2)];return{x:catmull(a,b,c,d,t,"x"),y:catmull(a,b,c,d,t,"y"),z:catmull(a,b,c,d,t,"z"),width:catmull(a,b,c,d,t,"width"),source};}
function sampleCurve(){const out=[];for(let i=0;i<pts.length-1;i++){for(let s=0;s<16;s++)out.push(curvePointAtSource(i+s/16));}out.push({...pts[pts.length-1],source:pts.length-1});return out;}
function arcLength(){const s=sampleCurve();let L=0;for(let i=1;i<s.length;i++)L+=Math.hypot(s[i].x-s[i-1].x,s[i].y-s[i-1].y);return L;}

function bodyThicknessWorld(p,index,total){const scale=Math.max(currentScale(),1e-6);return bodyThickness(p.z,index,total,p.width,p.source??0)/scale;}
function headMouthWorld(samples=null){samples=samples||sampleCurve();if(samples.length<2)return{x:pts[0]?.x||0,y:pts[0]?.y||0};const p=samples[0],next=samples[1],sx=p.x,sy=-p.y,nx=next.x,ny=-next.y,angle=Math.atan2(sy-ny,sx-nx)+rad(endpoint.headRotation),radius=bodyThicknessWorld(p,0,samples.length)*endpoint.headSize,lx=radius*.98,ly=radius*.17,c=Math.cos(angle),sn=Math.sin(angle),mx=sx+lx*c-ly*sn,my=sy+lx*sn+ly*c;return{x:mx,y:-my};}
function tailTipWorld(samples=null){samples=samples||sampleCurve();const n=samples.length;if(n<2)return{x:pts[pts.length-1]?.x||0,y:pts[pts.length-1]?.y||0};const p=samples[n-1],q=samples[n-2],sx=p.x,sy=-p.y,qx=q.x,qy=-q.y,angle=Math.atan2(sy-qy,sx-qx)+rad(endpoint.tailDirection),ux=Math.cos(angle),uy=Math.sin(angle),nx=-uy,ny=ux,width=bodyThicknessWorld(p,n-1,n)*endpoint.tailWidth,length=width*1.7*endpoint.tailLength,curve=endpoint.tailCurvature*width,tx=sx+ux*length+nx*curve,ty=sy+uy*length+ny*curve;return{x:tx,y:-ty};}
function biteAnchorsWorld(){const samples=sampleCurve();return{mouth:headMouthWorld(samples),tip:tailTipWorld(samples)};}
function translateEndpointSide(index,dx,dy){if(!Number.isFinite(dx)||!Number.isFinite(dy)||pts.length<3)return;const last=pts.length-1,dir=index===0?1:-1,weights=[1,.62,.24];for(let k=0;k<weights.length;k++){const j=index+dir*k;if(j<0||j>last)break;pts[j].x+=dx*weights[k];pts[j].y+=dy*weights[k];}}
function enforceBiteVisual(authoritativeIndex=null){if(!biteTail||pts.length<3)return;const last=pts.length-1,target=authoritativeIndex===0?last:0;for(let iter=0;iter<6;iter++){const{mouth,tip}=biteAnchorsWorld(),dx=target===last?mouth.x-tip.x:tip.x-mouth.x,dy=target===last?mouth.y-tip.y:tip.y-mouth.y,d=Math.hypot(dx,dy);if(!Number.isFinite(d)||d<.004)return;const maxStep=Math.max(.18,.55*snakeScale),k=Math.min(1,maxStep/d);translateEndpointSide(target,dx*k,dy*k);}}
function preserveEndpointCorrection(index,dx,dy){if(!preserveLength||!Number.isFinite(preserveTarget)||pts.length<4)return;const last=pts.length-1;if(index!==0&&index!==last)return;const dir=index===0?1:-1;const weights=[.68,.42,.22,.10];for(let k=1;k<=weights.length;k++){const j=index+dir*k;if(j<=0||j>=last)break;pts[j].x+=dx*weights[k-1];pts[j].y+=dy*weights[k-1];}
for(let iter=0;iter<8;iter++){const current=arcLength(),error=current-preserveTarget;if(!Number.isFinite(current)||!Number.isFinite(error))return;if(Math.abs(error)<.002)return;const j=index+dir,k=j+dir;if(j<=0||j>=last||k<0||k>last)return;const vx=pts[j].x-pts[index].x,vy=pts[j].y-pts[index].y,L=Math.hypot(vx,vy);if(!Number.isFinite(L)||L<1e-6)return;const ux=vx/L,uy=vy/L,maxStep=Math.max(.002,L*.25),step=clamp(error*.42,-maxStep,maxStep);const before=arcLength();const ox=pts[j].x,oy=pts[j].y,okx=pts[k].x,oky=pts[k].y;pts[j].x-=ux*step;pts[j].y-=uy*step;if(k!==last&&k!==0){pts[k].x-=ux*step*.32;pts[k].y-=uy*step*.32;}const after=arcLength();if(!Number.isFinite(after)||Math.abs(after-preserveTarget)>Math.abs(before-preserveTarget)+1e-6){pts[j].x=ox;pts[j].y=oy;pts[k].x=okx;pts[k].y=oky;return;}}
}
function movePoint(index,dx,dy){if(index<0||index>=pts.length||!Number.isFinite(dx)||!Number.isFinite(dy))return;pts[index].x+=dx;pts[index].y+=dy;const endpointDrag=index===0||index===pts.length-1;if(endpointDrag){preserveEndpointCorrection(index,dx,dy);if(biteTail){enforceBiteVisual(index);if(preserveLength){preserveEndpointCorrection(index,0,0);enforceBiteVisual(index);}}}else if(preserveLength){preserveTarget=arcLength();}}
function setSelectedCoordinate(axis,value){if(selected<0||!Number.isFinite(value))return;const p=pts[selected],delta=value-p[axis];if(axis==="x")movePoint(selected,delta,0);else movePoint(selected,0,delta);}
function setSelectedScalar(key,value){if(selected<0||!Number.isFinite(value))return;pts[selected][key]=value;if(biteTail&&(selected===0||selected===pts.length-1))enforceBiteVisual(selected);}
const headBiteKeys=new Set(["headSize","headRotation","neckWidth","mouthOpen"]),tailBiteKeys=new Set(["tailLength","tailWidth","tailDirection","tailCurvature"]);
function setEndpointValue(key,value){endpoint[key]=value;if(!biteTail)return;if(headBiteKeys.has(key))enforceBiteVisual(0);else if(tailBiteKeys.has(key))enforceBiteVisual(pts.length-1);}
function setBiteState(next){next=!!next;if(next===biteTail)return;const before=sceneState();biteTail=next;if(biteTail)enforceBiteVisual(null);if(preserveLength)preserveTarget=arcLength();commit(before);syncAllUI();draw();syncSparkleAnimation();}
function setPreserveLength(next){next=!!next;if(next===preserveLength)return;const before=sceneState();preserveLength=next;preserveTarget=next?arcLength():null;commit(before);syncAllUI();draw();}

function bodyThickness(z,index,total,widthMul=1,source=0){const progress=index/(total-1),tailFactor=1-.62*Math.pow(progress,10),neck=source<1.5?endpoint.neckWidth+(1-endpoint.neckWidth)*clamp(source/1.5,0,1):1;return .34*currentScale()*depthScale(z)*tailFactor*clamp(widthMul,.2,3)*neck;}
function earthApparentRadius(){return earth.r*earth.scale*depthScale(earth.depth);}
function earthFrontDepth(x,y){const dx=x-earth.x,dy=y-earth.y,r=earthApparentRadius(),radial2=dx*dx+dy*dy;if(radial2>r*r)return null;return earth.depth+Math.sqrt(Math.max(0,r*r-radial2));}
function nearestControlIndex(source){return clamp(Math.round(source),0,pts.length-1);}
function isBehindEarth(p,width){const idx=nearestControlIndex(p.source??0),override=pts[idx].earth;if(override==="FRONT_OF_EARTH")return false;if(override==="BEHIND_EARTH")return true;const front=earthFrontDepth(p.x,p.y);if(front===null)return false;const bodyRadiusWorld=(width/currentScale())*.36;return p.z+bodyRadiusWorld<front;}

function segmentIntersection(a,b,c,d){const r={x:b.x-a.x,y:b.y-a.y},s={x:d.x-c.x,y:d.y-c.y},den=r.x*s.y-r.y*s.x;if(Math.abs(den)<1e-6)return null;const q={x:c.x-a.x,y:c.y-a.y},t=(q.x*s.y-q.y*s.x)/den,u=(q.x*r.y-q.y*r.x)/den;if(t<=.02||t>=.98||u<=.02||u>=.98)return null;return{x:a.x+r.x*t,y:a.y+r.y*t,t,u};}
function crossingKey(a,b,ordinal=null){const lo=Math.min(a,b),hi=Math.max(a,b);return ordinal===null?`${lo}:${hi}`:`${lo}:${hi}:${ordinal}`;}
function detectCrossings(screen){const grouped=new Map();for(let i=0;i<screen.length-1;i++){const spanA=Math.floor(screen[i].original.source);for(let j=i+5;j<screen.length-1;j++){const spanB=Math.floor(screen[j].original.source);if(Math.abs(spanA-spanB)<=1)continue;const hit=segmentIntersection(screen[i],screen[i+1],screen[j],screen[j+1]);if(!hit)continue;const lo=Math.min(spanA,spanB),hi=Math.max(spanA,spanB),pair=crossingKey(lo,hi),srcA=lerp(screen[i].original.source,screen[i+1].original.source,hit.t),srcB=lerp(screen[j].original.source,screen[j+1].original.source,hit.u),zA=lerp(screen[i].z,screen[i+1].z,hit.t),zB=lerp(screen[j].z,screen[j+1].z,hit.u);let lowSeg,highSeg,zLow,zHigh,sourceLow,sourceHigh;if(spanA===lo){lowSeg=i;highSeg=j;zLow=zA;zHigh=zB;sourceLow=srcA;sourceHigh=srcB;}else{lowSeg=j;highSeg=i;zLow=zB;zHigh=zA;sourceLow=srcB;sourceHigh=srcA;}const list=grouped.get(pair)||[];if(list.some(c=>Math.hypot(c.x-hit.x,c.y-hit.y)<4&&Math.abs(c.sourceLow-sourceLow)<.05&&Math.abs(c.sourceHigh-sourceHigh)<.05))continue;list.push({spanLow:lo,spanHigh:hi,x:hit.x,y:hit.y,lowSeg,highSeg,zLow,zHigh,sourceLow,sourceHigh});grouped.set(pair,list);}}const found=[];for(const[pair,list]of grouped){list.sort((a,b)=>a.sourceLow-b.sourceLow||a.sourceHigh-b.sourceHigh);list.forEach((c,ordinal)=>{const key=crossingKey(c.spanLow,c.spanHigh,ordinal),legacyKey=crossingKey(c.spanLow,c.spanHigh),forced=crossingOverrides[key]??(ordinal===0?crossingOverrides[legacyKey]:undefined);let lowFront;if(forced==="LOW_FRONT"||forced==="A_FRONT")lowFront=true;else if(forced==="HIGH_FRONT"||forced==="B_FRONT")lowFront=false;else lowFront=c.zLow>=c.zHigh;found.push({...c,key,lowFront,forced:!!forced});});}return found;}
function markBehindRange(screen,index){for(let k=Math.max(0,index-2);k<=Math.min(screen.length-1,index+3);k++)screen[k].behindSnake=true;}
function classify(samples){const screen=samples.map((p,i)=>{const s=project(p),width=bodyThickness(p.z,i,samples.length,p.width,p.source);return{...s,original:p,width,behindEarth:isBehindEarth(p,width),behindSnake:false};});const crossings=detectCrossings(screen);for(const c of crossings)markBehindRange(screen,c.lowFront?c.highSeg:c.lowSeg);screen.crossings=crossings;return screen;}
function occType(p){if(p.behindEarth&&p.behindSnake)return"both";if(p.behindEarth)return"earth";if(p.behindSnake)return"snake";return"visible";}

const PS1_GOLD=[[86,53,12],[124,79,18],[169,114,27],[214,158,43],[247,210,99]];
const PS1_OCEAN=[[19,39,70],[28,57,91],[38,76,112],[57,101,139],[83,130,164]];
const PS1_LAND=[[70,91,47],[91,113,58],[116,137,68],[143,159,83]];
const artSnap=v=>Math.round(v);
function rgb(c,a=1){return`rgba(${c[0]},${c[1]},${c[2]},${a})`;}
function ps1Poly(points,fill,stroke=null,lineWidth=1){if(!points.length)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.setLineDash([]);ctx.stroke();}}
let ditherPatternCache=null;
function ditherPattern(){if(ditherPatternCache)return ditherPatternCache;const c=document.createElement("canvas"),g=c.getContext("2d");c.width=c.height=4;g.clearRect(0,0,4,4);g.fillStyle="#fff";g.fillRect(0,0,1,1);g.fillRect(2,2,1,1);ditherPatternCache=ctx.createPattern(c,"repeat");return ditherPatternCache;}
function regularPoly(x,y,r,n,offset=0){const out=[];for(let i=0;i<n;i++){const a=offset+i*Math.PI*2/n;out.push({x:artSnap(x+Math.cos(a)*r),y:artSnap(y+Math.sin(a)*r)});}return out;}
function drawStars(){ctx.fillStyle="rgba(226,232,244,.48)";for(let i=0;i<105;i++){const x=artSnap((i*149.31)%W),y=artSnap((i*91.73)%H),r=i%14===0?2:1;ctx.fillRect(x,y,r,r);}}
function lightDot(nx,ny){const a=rad(lighting.direction),lx=Math.cos(a),ly=Math.sin(a);return clamp((nx*lx+ny*ly)*.5+.5,0,1);}
function moonState(){const a=rad(moon.angle);return{x:earth.x+Math.cos(a)*moon.radius,y:earth.y+Math.sin(a)*moon.radius,z:clamp(earth.depth+moon.relativeDepth,0,14)};}
function drawMoon(behindPass){if(!moon.visible)return;const m=moonState(),scale=currentScale(),x=cx+viewX+m.x*scale,y=cy+viewY-m.y*scale,r=moon.size*scale*depthScale(m.z),front=earthFrontDepth(m.x,m.y),behind=front!==null&&m.z<front;if(behind!==behindPass)return;const outer=regularPoly(x,y,r,9,Math.PI/9),shadow=regularPoly(x+r*.12,y+r*.12,r*.96,9,Math.PI/9);if(lighting.shadows)ps1Poly(shadow,"rgba(0,0,0,.22)");ps1Poly(outer,"#9ca1a8","#454a52",1.5);ctx.save();ctx.beginPath();ctx.moveTo(outer[0].x,outer[0].y);for(let i=1;i<outer.length;i++)ctx.lineTo(outer[i].x,outer[i].y);ctx.closePath();ctx.clip();ps1Poly([{x:x-r,y:y-r*.7},{x:x+r*.25,y:y-r},{x:x-r*.05,y:y+r*.2}],"#c7c9c9");ps1Poly([{x:x-r*.05,y:y+r*.2},{x:x+r,y:y-r*.1},{x:x+r,y:y+r}],"#747a83");ctx.restore();if(diagnosticMode&&!cleanMode&&showLabels){ctx.fillStyle="#ddd";ctx.font="10px -apple-system";ctx.textAlign="center";ctx.fillText(`Moon ${m.z.toFixed(1)}`,x,y-r-7);}}
function drawEarth(){const scale=currentScale(),x=cx+viewX+earth.x*scale,y=cy+viewY-earth.y*scale,r=earthApparentRadius()*scale,alpha=earth.alpha;ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.fillStyle=rgb(PS1_OCEAN[1],alpha);ctx.fillRect(x-r,y-r,r*2,r*2);const lightA=rad(lighting.direction),centre={x:artSnap(x-Math.cos(lightA)*r*.12),y:artSnap(y-Math.sin(lightA)*r*.12)};for(let i=0;i<14;i++){const a0=-Math.PI/2+i*Math.PI*2/14,a1=-Math.PI/2+(i+1)*Math.PI*2/14,mid=(a0+a1)/2,lit=clamp((Math.cos(mid-lightA)+1)*.5*(lighting.enabled?lighting.intensity:0)+.18,0,1),shade=clamp(Math.round(lit*4),0,4),p0={x:artSnap(x+Math.cos(a0)*r*1.04),y:artSnap(y+Math.sin(a0)*r*1.04)},p1={x:artSnap(x+Math.cos(a1)*r*1.04),y:artSnap(y+Math.sin(a1)*r*1.04)};ps1Poly([centre,p0,p1],rgb(PS1_OCEAN[shade],alpha));}
const land=[[[-.72,-.58],[-.47,-.73],[-.20,-.60],[-.15,-.38],[-.34,-.27],[-.55,-.34]],[[-.03,-.35],[.24,-.53],[.54,-.40],[.67,-.13],[.49,.06],[.25,.03],[.12,.28],[-.08,.17]],[[-.25,.38],[.02,.27],[.29,.38],[.22,.62],[-.03,.73],[-.28,.61]]];land.forEach((shape,j)=>{const points=shape.map(([px,py])=>({x:artSnap(x+px*r),y:artSnap(y+py*r)}));ps1Poly(points,rgb(PS1_LAND[1+j%3],.88*alpha),rgb(PS1_LAND[0],.38*alpha),1);});const pat=ditherPattern();if(pat){ctx.globalAlpha=.09*alpha;ctx.fillStyle=pat;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.globalAlpha=1;}ctx.restore();ctx.strokeStyle=`rgba(174,198,218,${.7*alpha})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();if(diagnosticMode&&!cleanMode&&showLabels){ctx.fillStyle="#d8eaff";ctx.font="10px -apple-system";ctx.textAlign="center";ctx.fillText(`Earth ${earth.depth.toFixed(1)}`,x,y-r-8);}if(!earth.locked&&diagnosticMode&&!cleanMode){ctx.strokeStyle="rgba(120,220,255,.65)";ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(x,y,r+5,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}
function diagnosticStyle(type){if(type==="earth")return{body:"#a66ed2",hash:"#f2dcff"};if(type==="snake")return{body:"#e59445",hash:"#ffe0b9"};if(type==="both")return{body:"#da5aae",hash:"#ffd5ee"};return{body:"#8fa96d",hash:"#263020"};}
function drawStroke(a,b,color,width){ctx.lineCap="round";ctx.lineJoin="round";ctx.setLineDash([]);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
function drawVariableRibbon(run,widthScale,color){if(run.length<2)return;const left=[],right=[];for(let i=0;i<run.length;i++){const prev=run[Math.max(0,i-1)],next=run[Math.min(run.length-1,i+1)],dx=next.x-prev.x,dy=next.y-prev.y,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,half=run[i].width*widthScale*.5;left.push({x:run[i].x+nx*half,y:run[i].y+ny*half});right.push({x:run[i].x-nx*half,y:run[i].y-ny*half});}ctx.save();ctx.setLineDash([]);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(left[0].x,left[0].y);for(let i=1;i<left.length;i++)ctx.lineTo(left[i].x,left[i].y);for(let i=right.length-1;i>=0;i--)ctx.lineTo(right[i].x,right[i].y);ctx.closePath();ctx.fill();ctx.restore();}
function segmentLight(a,b){if(!lighting.enabled)return 0;const dx=b.y-a.y,dy=-(b.x-a.x),L=Math.hypot(dx,dy)||1;return lightDot(dx/L,dy/L)*lighting.intensity;}
function fogRGB(c,z){const amount=clamp((6.5-z)/6.5,0,1)*clamp(+lighting.depthFog||0,0,.5);return[Math.round(lerp(c[0],38,amount)),Math.round(lerp(c[1],42,amount)),Math.round(lerp(c[2],52,amount))];}
function goldShade(index,z,a=1){return rgb(fogRGB(PS1_GOLD[clamp(index,0,PS1_GOLD.length-1)],z),a);}
function coarseRun(run){if(run.length<=3)return run.slice();const out=[run[0]];for(let i=4;i<run.length-1;i+=4)out.push(run[i]);if(out[out.length-1]!==run[run.length-1])out.push(run[run.length-1]);return out;}
function facetGeom(a,b,scale=.48){const dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy)||1,nx=-dy/L,ny=dx/L,ha=a.width*scale,hb=b.width*scale,ca={x:artSnap(a.x),y:artSnap(a.y)},cb={x:artSnap(b.x),y:artSnap(b.y)};return{ca,cb,la:{x:artSnap(a.x+nx*ha),y:artSnap(a.y+ny*ha)},lb:{x:artSnap(b.x+nx*hb),y:artSnap(b.y+ny*hb)},ra:{x:artSnap(a.x-nx*ha),y:artSnap(a.y-ny*ha)},rb:{x:artSnap(b.x-nx*hb),y:artSnap(b.y-ny*hb)},nx,ny};}
function drawFacetSection(a,b,i){const g=facetGeom(a,b),z=(a.z+b.z)/2,li=segmentLight(a,b),base=clamp(Math.round(1+li*2.2),0,4),side=lightDot(g.nx,g.ny)>=.5,left=clamp(base+(side?1:-1),0,4),right=clamp(base+(side?-1:1),0,4);ps1Poly([g.la,g.lb,g.cb,g.ca],goldShade(left,z));ps1Poly([g.ca,g.cb,g.rb,g.ra],goldShade(right,z));const tri=i%2===0?[g.ca,g.lb,g.cb]:[g.ca,g.cb,g.ra];ps1Poly(tri,goldShade(clamp(base+1,0,4),z,.34));ctx.strokeStyle="rgba(54,34,10,.34)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.ca.x,g.ca.y);ctx.lineTo(g.cb.x,g.cb.y);ctx.stroke();if(i%3===0){ctx.save();ctx.beginPath();ctx.moveTo(g.la.x,g.la.y);ctx.lineTo(g.lb.x,g.lb.y);ctx.lineTo(g.rb.x,g.rb.y);ctx.lineTo(g.ra.x,g.ra.y);ctx.closePath();ctx.clip();const pat=ditherPattern();if(pat){ctx.globalAlpha=.065;ctx.fillStyle=pat;const xs=[g.la.x,g.ra.x,g.lb.x,g.rb.x],ys=[g.la.y,g.ra.y,g.lb.y,g.rb.y],minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);ctx.fillRect(minX-2,minY-2,Math.max(4,maxX-minX+4),Math.max(4,maxY-minY+4));}ctx.restore();}}
function drawPS1Run(run){const coarse=coarseRun(run);if(coarse.length<2)return;if(display.outline)drawVariableRibbon(coarse,1+display.outlineThickness*2.2,"#3b270b");for(let i=1;i<coarse.length;i++)drawFacetSection(coarse[i-1],coarse[i],i);}
function drawHiddenSegment(a,b,type){if(!showXray||cleanMode)return;const width=(a.width+b.width)/2,style=diagnosticStyle(type);ctx.lineCap="round";ctx.strokeStyle=style.body;ctx.lineWidth=width;ctx.setLineDash([Math.max(6,width*.30),Math.max(5,width*.18)]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);const dx=b.x-a.x,dy=b.y-a.y,L=Math.hypot(dx,dy);if(L<2)return;const ux=dx/L,uy=dy/L,nx=-uy,ny=ux,spacing=Math.max(9,width*.37),len=width*.46;ctx.strokeStyle=style.hash;ctx.lineWidth=Math.max(1.2,width*.05);for(let d=spacing*.5;d<L;d+=spacing){const x=a.x+ux*d,y=a.y+uy*d;ctx.beginPath();ctx.moveTo(x-nx*len-ux*len*.25,y-ny*len-uy*len*.25);ctx.lineTo(x+nx*len+ux*len*.25,y+ny*len+uy*len*.25);ctx.stroke();if(type==="both"){ctx.beginPath();ctx.moveTo(x+nx*len-ux*len*.25,y+ny*len-uy*len*.25);ctx.lineTo(x-nx*len+ux*len*.25,y-ny*len+uy*len*.25);ctx.stroke();}}}
function drawSnake(screen){for(let i=1;i<screen.length;i++){const a=screen[i-1],b=screen[i],aa=occType(a),bb=occType(b);let type="visible";if(aa==="both"||bb==="both")type="both";else if(aa==="earth"||bb==="earth")type="earth";else if(aa==="snake"||bb==="snake")type="snake";if(type!=="visible")drawHiddenSegment(a,b,type);}let run=[];const flush=()=>{if(run.length>1)drawPS1Run(run);run=[];};for(let i=1;i<screen.length;i++){const a=screen[i-1],b=screen[i],visible=occType(a)==="visible"&&occType(b)==="visible";if(visible){if(!run.length)run.push(a);run.push(b);}else flush();}flush();}
function headGeometry(screen){const p=screen[0],next=screen[1],base=Math.atan2(p.y-next.y,p.x-next.x),angle=base+rad(endpoint.headRotation),radius=p.width*endpoint.headSize;return{p,next,angle,radius};}
function headEyeScreen(screen){const{p,angle,radius}=headGeometry(screen),exLocal=radius*endpoint.eyeX,eyLocal=radius*endpoint.eyeY,c=Math.cos(angle),sn=Math.sin(angle);return{x:p.x+exLocal*c-eyLocal*sn,y:p.y+exLocal*sn+eyLocal*c,radius,angle};}
function drawHead(screen){const{p,angle,radius}=headGeometry(screen),type=occType(p),style=diagnosticStyle(type),visible=type==="visible",outline=visible?"#3b270b":style.hash,coords=[[1.30,.04],[1.08,-.48],[.42,-.78],[-.52,-.76],[-1.18,-.38],[-1.32,.12],[-.88,.66],[.08,.82],[.86,.56]];ctx.save();ctx.translate(artSnap(p.x),artSnap(p.y));ctx.rotate(angle);ctx.beginPath();ctx.moveTo(coords[0][0]*radius,coords[0][1]*radius);for(let i=1;i<coords.length;i++)ctx.lineTo(coords[i][0]*radius,coords[i][1]*radius);ctx.closePath();ctx.fillStyle=visible?goldShade(2,p.z):style.body;ctx.fill();ctx.save();ctx.clip();if(visible){ps1Poly([{x:-1.3*radius,y:-.1*radius},{x:.25*radius,y:-.82*radius},{x:.52*radius,y:.02*radius}],goldShade(4,p.z));ps1Poly([{x:.52*radius,y:.02*radius},{x:1.35*radius,y:-.18*radius},{x:1.25*radius,y:.58*radius},{x:-.15*radius,y:.78*radius}],goldShade(1,p.z));const pat=ditherPattern();if(pat){ctx.globalAlpha=.07;ctx.fillStyle=pat;ctx.fillRect(-radius*1.4,-radius*.9,radius*2.8,radius*1.8);ctx.globalAlpha=1;}}ctx.restore();ctx.strokeStyle=outline;ctx.lineWidth=Math.max(1.5,radius*.055);ctx.stroke();const ex=radius*endpoint.eyeX,ey=radius*endpoint.eyeY,eyeH=Math.max(1.2,radius*.18*endpoint.eyeOpen);ctx.fillStyle="#f2e7bd";ctx.beginPath();ctx.ellipse(ex,ey,radius*.19,eyeH,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#5d3b0d";ctx.lineWidth=Math.max(1,radius*.025);ctx.stroke();const ga=rad(endpoint.gazeDirection-angle*180/Math.PI),px=ex+Math.cos(ga)*radius*.08,py=ey+Math.sin(ga)*radius*.08;ctx.fillStyle="#15110c";ctx.beginPath();ctx.rect(px-Math.max(1.2,radius*.055),py-Math.max(1.2,radius*.055),Math.max(2.4,radius*.11),Math.max(2.4,radius*.11));ctx.fill();ctx.strokeStyle=outline;ctx.lineWidth=Math.max(1.2,radius*.055);ctx.beginPath();ctx.moveTo(radius*.38,radius*.25);ctx.lineTo(radius*.70,radius*(.29+.18*endpoint.mouthOpen));ctx.lineTo(radius*.98,radius*.17);ctx.stroke();ctx.restore();if(display.gazeArrow&&diagnosticMode&&!cleanMode)drawGazeArrow(screen);}
function drawGazeArrow(screen){const eye=headEyeScreen(screen),a=rad(endpoint.gazeDirection),len=Math.max(38,eye.radius*2.2),alpha=clamp(+display.gazeOpacity||0,0,1);ctx.strokeStyle=`rgba(100,220,255,${alpha})`;ctx.fillStyle=`rgba(100,220,255,${alpha})`;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(eye.x,eye.y);ctx.lineTo(eye.x+Math.cos(a)*len,eye.y+Math.sin(a)*len);ctx.stroke();ctx.save();ctx.translate(eye.x+Math.cos(a)*len,eye.y+Math.sin(a)*len);ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-9,-5);ctx.lineTo(-9,5);ctx.closePath();ctx.fill();ctx.restore();}
function tailScreenGeometry(screen){const n=screen.length,p=screen[n-1],q=screen[n-2],base=Math.atan2(p.y-q.y,p.x-q.x)+rad(endpoint.tailDirection),ux=Math.cos(base),uy=Math.sin(base),nx=-uy,ny=ux,width=p.width*endpoint.tailWidth,length=width*1.7*endpoint.tailLength,curve=endpoint.tailCurvature*width,tip={x:artSnap(p.x+ux*length+nx*curve),y:artSnap(p.y+uy*length+ny*curve)},baseL={x:artSnap(p.x-ux*width*.35+nx*width),y:artSnap(p.y-uy*width*.35+ny*width)},baseR={x:artSnap(p.x-ux*width*.35-nx*width),y:artSnap(p.y-uy*width*.35-ny*width)},midL={x:artSnap(p.x+ux*length*.48+nx*(curve*.58+width*.55)),y:artSnap(p.y+uy*length*.48+ny*(curve*.58+width*.55))},midR={x:artSnap(p.x+ux*length*.48+nx*(curve*.58-width*.55)),y:artSnap(p.y+uy*length*.48+ny*(curve*.58-width*.55))};return{p,q,tip,baseL,baseR,midL,midR,width};}
function drawTail(screen){const g=tailScreenGeometry(screen),type=occType(g.p),style=diagnosticStyle(type),visible=type==="visible",shape=[g.tip,g.midL,g.baseL,g.baseR,g.midR];ps1Poly(shape,visible?goldShade(2,g.p.z):style.body,visible?"#3b270b":style.hash,2);if(visible){ps1Poly([g.tip,g.midL,g.midR],goldShade(4,g.p.z,.62));ps1Poly([g.midL,g.baseL,g.baseR,g.midR],goldShade(1,g.p.z,.46));}}
function drawSpriteStar(x,y,size,level){const palette=["#b7c6dc","#e7e2b6","#fff0a0","#fff8d2"],c=palette[clamp(level,0,3)],sizePx=Math.max(1,size);ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(artSnap(x),artSnap(y-sizePx*1.7));ctx.lineTo(artSnap(x+sizePx*.55),artSnap(y-sizePx*.55));ctx.lineTo(artSnap(x+sizePx*1.7),artSnap(y));ctx.lineTo(artSnap(x+sizePx*.55),artSnap(y+sizePx*.55));ctx.lineTo(artSnap(x),artSnap(y+sizePx*1.7));ctx.lineTo(artSnap(x-sizePx*.55),artSnap(y+sizePx*.55));ctx.lineTo(artSnap(x-sizePx*1.7),artSnap(y));ctx.lineTo(artSnap(x-sizePx*.55),artSnap(y-sizePx*.55));ctx.closePath();ctx.fill();}
function drawGazeSparkles(screen){if(biteTail||!display.gazeStars||occType(screen[0])!=="visible")return;const eye=headEyeScreen(screen),a=rad(endpoint.gazeDirection),ux=Math.cos(a),uy=Math.sin(a),nx=-uy,ny=ux,layout=[[1.65,-.25],[2.20,.28],[2.75,-.10],[3.28,.38],[3.86,-.31],[4.42,.10]];for(let i=0;i<layout.length;i++){const[d,o]=layout[i],phase=(Math.floor(sparkleFrame/(1+i%3))+i*2)%4,x=eye.x+ux*eye.radius*d+nx*eye.radius*o,y=eye.y+uy*eye.radius*d+ny*eye.radius*o;drawSpriteStar(x,y,1.5+(phase===3?1.8:phase*.35),phase);}const ephase=sparkleFrame%4;drawSpriteStar(eye.x-eye.radius*.055,eye.y-eye.radius*.075,1.2+(ephase===3?1.4:ephase*.25),Math.min(3,1+ephase));}
function syncSparkleAnimation(){const active=!biteTail&&!!display.gazeStars&&!document.hidden;if(active&&!sparkleTimer){sparkleTimer=setInterval(()=>{sparkleFrame=(sparkleFrame+1)%840;draw();},120);}else if(!active&&sparkleTimer){clearInterval(sparkleTimer);sparkleTimer=0;}}
function drawDirectionArrows(screen){if(!showArrows)return;const reversed=[...screen].reverse();let acc=0;const spacing=58*viewZoom;for(let i=1;i<reversed.length;i++){const a=reversed[i-1],b=reversed[i],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);acc+=len;if(acc<spacing)continue;acc=0;const angle=Math.atan2(dy,dx),x=(a.x+b.x)/2,y=(a.y+b.y)/2,size=Math.max(5,8*viewZoom);ctx.save();ctx.translate(artSnap(x),artSnap(y));ctx.rotate(angle);ctx.fillStyle="rgba(255,232,128,.96)";ctx.beginPath();ctx.moveTo(size,0);ctx.lineTo(-size*.62,-size*.62);ctx.lineTo(-size*.62,size*.62);ctx.closePath();ctx.fill();ctx.restore();}}
function depthPointColour(z){const t=clamp((z-6.5)/7,-1,1);return t>=0?`rgb(${Math.round(255-115*t)},${Math.round(255-20*t)},255)`:`rgb(255,${Math.round(255-110*Math.abs(t))},255)`;}
function drawPoints(){if(!showPoints||cleanMode)return;pts.forEach((p,i)=>{const s=project(p),head=i===0,tail=i===pts.length-1,markerScale=clamp(viewZoom,.75,1.6);ctx.fillStyle=head?"#83e3ff":tail?"#ffd479":depthPointColour(p.z);ctx.strokeStyle=i===selected?"#fff36b":"#111";ctx.lineWidth=i===selected?4:2;ctx.beginPath();if(tail){const r=8*markerScale;ctx.moveTo(s.x,s.y-r);ctx.lineTo(s.x+r,s.y);ctx.lineTo(s.x,s.y+r);ctx.lineTo(s.x-r,s.y);ctx.closePath();}else ctx.arc(s.x,s.y,(head?9:7)*markerScale,0,Math.PI*2);ctx.fill();ctx.stroke();if(showLabels){ctx.fillStyle="rgba(255,255,255,.88)";ctx.font=`${10*markerScale}px -apple-system`;ctx.textAlign="center";ctx.fillText((showNumbers?`${i}: `:"")+p.z.toFixed(1),s.x,s.y-13*markerScale);}if(p.earth!=="AUTO"){ctx.fillStyle=p.earth==="FRONT_OF_EARTH"?"#45e6f5":"#ff5f6d";ctx.beginPath();ctx.arc(s.x+10*markerScale,s.y+9*markerScale,3.5*markerScale,0,Math.PI*2);ctx.fill();}if(showContacts&&p.contact==="TOUCHING_EARTH"){ctx.strokeStyle="#fff2a8";ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x,s.y,13*markerScale,0,Math.PI*2);ctx.stroke();}});}
function drawReferenceCircle(){if(!display.referenceCircle)return;const s=currentScale(),r=earth.r*1.24*s,x=cx+viewX+earth.x*s,y=cy+viewY-earth.y*s;ctx.strokeStyle="rgba(220,230,255,.24)";ctx.lineWidth=1.5;ctx.setLineDash([6,6]);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
function drawMouthTailGuide(){if(!display.mouthTailGuide)return;const anchors=biteAnchorsWorld(),a=project({...anchors.mouth,z:pts[0].z}),b=project({...anchors.tip,z:pts[pts.length-1].z}),d=Math.hypot(anchors.mouth.x-anchors.tip.x,anchors.mouth.y-anchors.tip.y);ctx.strokeStyle="rgba(120,220,255,.55)";ctx.lineWidth=1.5;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#9ee8ff";ctx.font="10px -apple-system";ctx.textAlign="center";ctx.fillText(d.toFixed(2),(a.x+b.x)/2,(a.y+b.y)/2-6);}
function drawClosurePreview(){if(!display.closurePreview)return;const anchors=biteAnchorsWorld(),hs=project({...anchors.mouth,z:pts[0].z}),ts=project({...anchors.tip,z:pts[pts.length-1].z}),mx=(hs.x+ts.x)/2,my=Math.min(hs.y,ts.y)-currentScale()*.55;ctx.strokeStyle="rgba(255,220,140,.48)";ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(hs.x,hs.y);ctx.lineTo(mx,my);ctx.lineTo(ts.x,ts.y);ctx.stroke();ctx.setLineDash([]);}
function drawTopologyMarkers(screen){if(cleanMode||!diagnosticMode)return;if(showTransitions){let last=occType(screen[0]);for(let i=1;i<screen.length;i++){const now=occType(screen[i]);if(now!==last){ctx.fillStyle="#fff";ctx.strokeStyle="#111";ctx.lineWidth=2;ctx.beginPath();ctx.arc(screen[i].x,screen[i].y,5,0,Math.PI*2);ctx.fill();ctx.stroke();last=now;}}}for(const c of screen.crossings||[]){ctx.fillStyle=c.forced?"#45e6f5":"#ffcf55";ctx.strokeStyle="#111";ctx.lineWidth=1.5;ctx.beginPath();ctx.rect(c.x-4,c.y-4,8,8);ctx.fill();ctx.stroke();}$("crossingInfo").textContent=`Crossings: ${(screen.crossings||[]).length}`;}
function drawContactShadows(){if(!lighting.shadows)return;for(const p of pts){if(p.contact!=="TOUCHING_EARTH")continue;const s=project(p),ex=project({x:earth.x,y:earth.y,z:earth.depth}),dx=s.x-ex.x,dy=s.y-ex.y,L=Math.hypot(dx,dy)||1,x=s.x-dx/L*7,y=s.y-dy/L*7;ctx.save();ctx.translate(artSnap(x),artSnap(y));ctx.rotate(Math.atan2(dy,dx));ctx.scale(1,.38);ps1Poly(regularPoly(0,0,14,8,Math.PI/8),"rgba(0,0,0,.24)");ctx.restore();}}
function draw(){ctx.clearRect(0,0,W,H);drawStars();drawReferenceCircle();drawMoon(true);drawEarth();drawMoon(false);drawContactShadows();const screen=classify(sampleCurve());drawSnake(screen);drawDirectionArrows(screen);drawHead(screen);drawTail(screen);drawGazeSparkles(screen);drawMouthTailGuide();drawClosurePreview();drawTopologyMarkers(screen);drawPoints();}

function nearestPoint(x,y,maxRadius=null){let best=-1,bestD=Infinity;pts.forEach((p,i)=>{const s=project(p),dx=s.x-x,dy=s.y-y,d=dx*dx+dy*dy;if(d<bestD){bestD=d;best=i;}});const hit=maxRadius??Math.max(24,30*clamp(viewZoom,.8,1.5));return bestD<hit*hit?best:-1;}
function nearestCurveLocation(x,y,maxDist=26){const samples=sampleCurve();let best=null,bestD=Infinity;for(let i=0;i<samples.length-1;i++){const a=project(samples[i]),b=project(samples[i+1]),vx=b.x-a.x,vy=b.y-a.y,L2=vx*vx+vy*vy;if(L2<1e-6)continue;const t=clamp(((x-a.x)*vx+(y-a.y)*vy)/L2,0,1),px=a.x+vx*t,py=a.y+vy*t,d=Math.hypot(x-px,y-py);if(d<bestD){bestD=d;best={x:lerp(samples[i].x,samples[i+1].x,t),y:lerp(samples[i].y,samples[i+1].y,t),z:lerp(samples[i].z,samples[i+1].z,t),width:lerp(samples[i].width,samples[i+1].width,t),source:lerp(samples[i].source,samples[i+1].source,t),screenX:px,screenY:py,distance:d};}}return bestD<=maxDist?best:null;}
function hitEarth(x,y){const s=currentScale(),ex=cx+viewX+earth.x*s,ey=cy+viewY-earth.y*s,r=earthApparentRadius()*s;return Math.hypot(x-ex,y-ey)<=r;}

function parseCrossingKey(key){const parts=String(key).split(":").map(Number),[a,b,ordinal]=parts;return Number.isFinite(a)&&Number.isFinite(b)?[a,b,Number.isFinite(ordinal)?ordinal:null]:null;}
function remapCrossingsOnInsert(index){const next={};for(const[key,val]of Object.entries(crossingOverrides)){const pair=parseCrossingKey(key);if(!pair)continue;let[a,b,ordinal]=pair;const split=index-1;if(a===split||b===split)continue;if(a>=index)a++;if(b>=index)b++;next[crossingKey(a,b,ordinal)]=val;}crossingOverrides=next;}
function remapCrossingsOnDelete(index){const next={};for(const[key,val]of Object.entries(crossingOverrides)){const pair=parseCrossingKey(key);if(!pair)continue;let[a,b,ordinal]=pair;if(a===index-1||a===index||b===index-1||b===index)continue;if(a>index)a--;if(b>index)b--;next[crossingKey(a,b,ordinal)]=val;}crossingOverrides=next;}
function insertPointAtLocation(loc){if(!loc)return -1;const span=clamp(Math.floor(loc.source),0,pts.length-2),index=span+1,a=pts[span],b=pts[span+1];remapCrossingsOnInsert(index);pts.splice(index,0,{x:loc.x,y:loc.y,z:clamp(loc.z,0,14),width:clamp(loc.width,.2,3),earth:a.earth===b.earth?a.earth:"AUTO",contact:a.contact===b.contact?a.contact:"AUTO"});selected=index;if(preserveLength)preserveTarget=arcLength();return index;}
function insertAtSource(source){return insertPointAtLocation(curvePointAtSource(clamp(source,.001,pts.length-1.001)));}
function deleteSelectedPoint(){if(selected<=0||selected>=pts.length-1||pts.length<=7)return false;const index=selected;remapCrossingsOnDelete(index);pts.splice(index,1);selected=Math.min(index,pts.length-2);if(preserveLength)preserveTarget=arcLength();return true;}
function duplicateSelectedPoint(){if(selected<0)return false;const src=pts[selected],index=Math.min(selected+1,pts.length-1);remapCrossingsOnInsert(index);pts.splice(index,0,{...clone(src),x:src.x+.08,y:src.y+.08});selected=index;if(preserveLength)preserveTarget=arcLength();return true;}

function depthWord(z){if(z>=9)return"NEAR";if(z<=4)return"FAR";return"NORMAL";}
function selectedName(){if(selected<0)return"NONE";if(selected===0)return"HEAD";if(selected===pts.length-1)return"TAIL";return"P"+selected;}
function syncEndpointControls(){const head=selected===0,tail=selected===pts.length-1;$("endpointControls").classList.toggle("hidden",!head&&!tail);$("headControls").classList.toggle("hidden",!head);$("tailControls").classList.toggle("hidden",!tail);if(head||tail)$("endpointTitle").textContent=head?"HEAD properties":"TAIL properties";}
function syncViewportUI(){$("viewZoom").value=viewZoom;$("viewZoomValue").textContent=viewZoom.toFixed(2)+"×";}
function setToggle(id,on,onText=null,offText=null){const el=$(id);if(!el)return;el.classList.toggle("active",!!on);if(onText)el.textContent=on?onText:offText;}
function syncNumericInputs(){for(const row of document.querySelectorAll(".numericRow")){const range=row.querySelector('input[type="range"]'),num=row.querySelector(".numericInput"),buttons=row.querySelectorAll(".stepBtn");if(!range||!num)continue;num.value=range.value;num.disabled=range.disabled;buttons.forEach(b=>b.disabled=range.disabled);}}
function syncAllUI(){const p=selected>=0?pts[selected]:null;$("selectionLabel").textContent=selectedName();$("pointX").disabled=!p;$("pointY").disabled=!p;$("depth").disabled=!p;$("pointWidth").disabled=!p;$("earthRelation").disabled=!p;$("contactState").disabled=!p;$("pointXValue").textContent=p?p.x.toFixed(2):"—";$("pointYValue").textContent=p?p.y.toFixed(2):"—";$("depthValue").textContent=p?p.z.toFixed(1):"—";$("pointWidthValue").textContent=p?p.width.toFixed(2)+"×":"—";$("handleDepth").textContent=p?`${depthWord(p.z)} ${p.z.toFixed(1)}`:"—";if(p){$("pointX").value=p.x;$("pointY").value=p.y;$("depth").value=p.z;$("pointWidth").value=p.width;$("earthRelation").value=p.earth;$("contactState").value=p.contact;}syncEndpointControls();$("snakeScale").value=snakeScale;$("scaleValue").textContent=snakeScale.toFixed(2)+"×";syncViewportUI();$("perspective").value=perspectiveStrength;$("perspectiveValue").textContent=perspectiveStrength.toFixed(2)+"×";$("arcLengthValue").textContent=arcLength().toFixed(3);$("outlineThickness").value=display.outlineThickness;$("outlineValue").textContent=display.outlineThickness.toFixed(2);setToggle("outlineToggle",display.outline);
for(const id of["headSize","headRotation","neckWidth","eyeOpen","eyeX","eyeY","gazeDirection","mouthOpen","tailLength","tailWidth","tailDirection","tailCurvature"])$(id).value=endpoint[id];$("headSizeValue").textContent=endpoint.headSize.toFixed(2)+"×";$("headRotationValue").textContent=endpoint.headRotation.toFixed(0)+"°";$("neckWidthValue").textContent=endpoint.neckWidth.toFixed(2)+"×";$("eyeOpenValue").textContent=endpoint.eyeOpen.toFixed(2);$("eyeXValue").textContent=endpoint.eyeX.toFixed(2);$("eyeYValue").textContent=endpoint.eyeY.toFixed(2);$("gazeDirectionValue").textContent=endpoint.gazeDirection.toFixed(0)+"°";$("mouthOpenValue").textContent=endpoint.mouthOpen.toFixed(2);$("tailLengthValue").textContent=endpoint.tailLength.toFixed(2)+"×";$("tailWidthValue").textContent=endpoint.tailWidth.toFixed(2)+"×";$("tailDirectionValue").textContent=endpoint.tailDirection.toFixed(0)+"°";$("tailCurvatureValue").textContent=endpoint.tailCurvature.toFixed(2);
$("earthX").value=earth.x;$("earthY").value=earth.y;$("earthDepth").value=earth.depth;$("earthScale").value=earth.scale;$("earthXValue").textContent=earth.x.toFixed(2);$("earthYValue").textContent=earth.y.toFixed(2);$("earthDepthValue").textContent=earth.depth.toFixed(1);$("earthScaleValue").textContent=earth.scale.toFixed(2)+"×";setToggle("earthLock",earth.locked,"Earth locked","Earth unlocked");setToggle("moonVisible",moon.visible,"Moon visible","Moon hidden");$("moonAngle").value=moon.angle;$("moonRadius").value=moon.radius;$("moonSize").value=moon.size;$("moonDepth").value=moon.relativeDepth;$("moonAngleValue").textContent=moon.angle.toFixed(0)+"°";$("moonRadiusValue").textContent=moon.radius.toFixed(2);$("moonSizeValue").textContent=moon.size.toFixed(2);$("moonDepthValue").textContent=(moon.relativeDepth>=0?"+":"")+moon.relativeDepth.toFixed(1);
$("lightDirection").value=lighting.direction;$("lightIntensity").value=lighting.intensity;$("lightSoftness").value=lighting.softness;$("lightDirectionValue").textContent=lighting.direction.toFixed(0)+"°";$("lightIntensityValue").textContent=lighting.intensity.toFixed(2);$("lightSoftnessValue").textContent=lighting.softness.toFixed(2);if($("depthFog")){$("depthFog").value=lighting.depthFog;$("depthFogValue").textContent=(+lighting.depthFog||0).toFixed(2);}if($("gazeOpacity")){$("gazeOpacity").value=display.gazeOpacity;$("gazeOpacityValue").textContent=(+display.gazeOpacity||0).toFixed(2);}setToggle("lightToggle",lighting.enabled);setToggle("shadowToggle",lighting.shadows);setToggle("transitionToggle",showTransitions);setToggle("contactToggle",showContacts);setToggle("referenceCircle",display.referenceCircle);setToggle("mouthTailGuide",display.mouthTailGuide);setToggle("closurePreview",display.closurePreview);setToggle("gazeArrow",display.gazeArrow);setToggle("gazeStarsToggle",display.gazeStars);setToggle("arrows",showArrows);setToggle("points",showPoints);setToggle("labels",showLabels);setToggle("xray",showXray);setToggle("numbers",showNumbers);setToggle("diagnosticMode",diagnosticMode);setToggle("cleanMode",cleanMode);setToggle("biteTailBtn",biteTail);setToggle("releaseTailBtn",!biteTail);setToggle("preserveLengthToggle",preserveLength,"Preserve length","Free length");if($("preserveLengthValue"))$("preserveLengthValue").textContent=preserveLength&&Number.isFinite(preserveTarget)?`target ${preserveTarget.toFixed(3)}`:"head/tail only";$("ghost").textContent=earth.alpha>.5?"Ghost Earth":"Solid Earth";syncNumericInputs();syncHistory();}

const rangeConfigs={
pointX:{apply:v=>{if(selected>=0)setSelectedCoordinate("x",v);}},pointY:{apply:v=>{if(selected>=0)setSelectedCoordinate("y",v);}},depth:{apply:v=>setSelectedScalar("z",v)},pointWidth:{apply:v=>setSelectedScalar("width",v)},
snakeScale:{apply:v=>{if(v<=0||Math.abs(v-snakeScale)<1e-10)return;const ratio=v/snakeScale;let mx=0,my=0;for(const p of pts){mx+=p.x;my+=p.y;}mx/=pts.length;my/=pts.length;for(const p of pts){p.x=mx+(p.x-mx)*ratio;p.y=my+(p.y-my)*ratio;}snakeScale=v;if(biteTail)enforceBiteVisual(null);if(preserveLength)preserveTarget=arcLength();}},
viewZoom:{history:false,apply:v=>{viewZoom=clamp(v,.35,4);}},perspective:{apply:v=>{perspectiveStrength=v;}},outlineThickness:{apply:v=>{display.outlineThickness=v;}},gazeOpacity:{apply:v=>display.gazeOpacity=v},
headSize:{apply:v=>setEndpointValue("headSize",v)},headRotation:{apply:v=>setEndpointValue("headRotation",v)},neckWidth:{apply:v=>setEndpointValue("neckWidth",v)},eyeOpen:{apply:v=>setEndpointValue("eyeOpen",v)},eyeX:{apply:v=>setEndpointValue("eyeX",v)},eyeY:{apply:v=>setEndpointValue("eyeY",v)},gazeDirection:{apply:v=>setEndpointValue("gazeDirection",v)},mouthOpen:{apply:v=>setEndpointValue("mouthOpen",v)},tailLength:{apply:v=>setEndpointValue("tailLength",v)},tailWidth:{apply:v=>setEndpointValue("tailWidth",v)},tailDirection:{apply:v=>setEndpointValue("tailDirection",v)},tailCurvature:{apply:v=>setEndpointValue("tailCurvature",v)},
earthX:{apply:v=>earth.x=v},earthY:{apply:v=>earth.y=v},earthDepth:{apply:v=>earth.depth=v},earthScale:{apply:v=>earth.scale=v},moonAngle:{apply:v=>moon.angle=v},moonRadius:{apply:v=>moon.radius=v},moonSize:{apply:v=>moon.size=v},moonDepth:{apply:v=>moon.relativeDepth=v},lightDirection:{apply:v=>lighting.direction=v},lightIntensity:{apply:v=>lighting.intensity=v},lightSoftness:{apply:v=>lighting.softness=v},depthFog:{apply:v=>lighting.depthFog=v}
};
const rangeEdits=new Map();
function rangePrecision(el){const step=String(el.step||"1");return step.includes(".")?step.split(".")[1].length:0;}
function normalizeRangeValue(el,v){const min=Number.isFinite(+el.min)?+el.min:-Infinity,max=Number.isFinite(+el.max)?+el.max:Infinity,step=+el.step||1;v=clamp(+v,min,max);if(Number.isFinite(min)){const n=Math.round((v-min)/step);v=min+n*step;}return +v.toFixed(Math.max(rangePrecision(el),4));}
function applyRange(id,v){const el=$(id),cfg=rangeConfigs[id];if(!el||!cfg||el.disabled)return;v=normalizeRangeValue(el,v);el.value=v;cfg.apply(v);syncAllUI();draw();if(cfg.history===false)scheduleAutosave();}
function armRange(el){const cfg=rangeConfigs[el.id];if(!cfg||cfg.history===false||rangeEdits.has(el))return;rangeEdits.set(el,sceneState());}
function finishRange(el){const cfg=rangeConfigs[el.id],before=rangeEdits.get(el);if(before&&cfg?.history!==false)commit(before);rangeEdits.delete(el);syncAllUI();}
function installTaskControls(){const body=$("sheetBody");if(!body)return;if(!$("constraintControls")){const section=document.createElement("div");section.id="constraintControls";section.className="section";section.innerHTML=`<div class="sectionTitle">Ouroboros state</div><div class="twoCol"><button id="biteTailBtn" type="button">Bite tail</button><button id="releaseTailBtn" type="button">Release tail</button></div><div class="controlRow readOnlyRow"><label>Length</label><button id="preserveLengthToggle" type="button">Free length</button></div><div class="subtle" id="preserveLengthValue">head/tail only</div>`;const firstSection=body.querySelector(".section");body.insertBefore(section,firstSection||body.firstChild);$("biteTailBtn").onclick=()=>setBiteState(true);$("releaseTailBtn").onclick=()=>setBiteState(false);$("preserveLengthToggle").onclick=()=>setPreserveLength(!preserveLength);}
if(!$("gazeStarsToggle")){const grid=$("gazeArrow")?.parentElement;if(grid){const btn=document.createElement("button");btn.id="gazeStarsToggle";btn.type="button";btn.textContent="Gaze stars";grid.appendChild(btn);btn.onclick=()=>mutate(()=>display.gazeStars=!display.gazeStars);}}
if(!$("gazeOpacity")){const guide=$("gazeArrow")?.closest(".section");if(guide){const row=document.createElement("div");row.className="controlRow";row.innerHTML=`<label>Gaze opacity</label><input id="gazeOpacity" type="range" min="0" max="1" step=".05" value="${display.gazeOpacity}"><div class="controlValue" id="gazeOpacityValue">${display.gazeOpacity.toFixed(2)}</div>`;guide.appendChild(row);}}
if(!$("depthFog")){const light=$("lightToggle")?.closest(".section");if(light){const row=document.createElement("div");row.className="controlRow";row.innerHTML=`<label>Depth fog</label><input id="depthFog" type="range" min="0" max=".5" step=".02" value="${lighting.depthFog}"><div class="controlValue" id="depthFogValue">${lighting.depthFog.toFixed(2)}</div>`;light.appendChild(row);}}
}
function enhanceNumericControls(){for(const el of document.querySelectorAll('input[type="range"]')){const row=el.closest(".controlRow");if(!row||!rangeConfigs[el.id])continue;row.classList.add("numericRow");const minus=document.createElement("button"),plus=document.createElement("button"),num=document.createElement("input");minus.type=plus.type="button";minus.textContent="−";plus.textContent="+";minus.className=plus.className="stepBtn";minus.setAttribute("aria-label",`Decrease ${el.id}`);plus.setAttribute("aria-label",`Increase ${el.id}`);num.type="number";num.className="numericInput";num.inputMode="decimal";num.min=el.min;num.max=el.max;num.step=el.step;num.value=el.value;num.setAttribute("aria-label",`Exact value for ${el.id}`);row.insertBefore(minus,el);const oldValue=row.querySelector(".controlValue");row.insertBefore(plus,oldValue);row.insertBefore(num,oldValue);
el.addEventListener("pointerdown",()=>armRange(el));el.addEventListener("keydown",()=>armRange(el));el.addEventListener("input",()=>applyRange(el.id,+el.value));el.addEventListener("change",()=>{applyRange(el.id,+el.value);finishRange(el);});el.addEventListener("pointerup",()=>finishRange(el));el.addEventListener("pointercancel",()=>finishRange(el));
let numBefore=null;num.addEventListener("focus",()=>{if(rangeConfigs[el.id].history!==false)numBefore=sceneState();});num.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();num.blur();}});num.addEventListener("change",()=>{const v=Number(num.value);if(Number.isFinite(v))applyRange(el.id,v);else num.value=el.value;if(numBefore){commit(numBefore);numBefore=null;}syncAllUI();});num.addEventListener("blur",()=>{if(numBefore){const v=Number(num.value);if(Number.isFinite(v))applyRange(el.id,v);commit(numBefore);numBefore=null;}syncAllUI();});
for(const[btn,dir]of[[minus,-1],[plus,1]]){let before=null,timer=0,interval=0,active=false;const stepOnce=()=>applyRange(el.id,+el.value+dir*(+el.step||1));const end=()=>{if(!active)return;active=false;clearTimeout(timer);clearInterval(interval);if(before){commit(before);before=null;}syncAllUI();};btn.addEventListener("pointerdown",e=>{if(el.disabled)return;e.preventDefault();active=true;if(rangeConfigs[el.id].history!==false)before=sceneState();stepOnce();timer=setTimeout(()=>{interval=setInterval(stepOnce,85);},360);btn.setPointerCapture?.(e.pointerId);});btn.addEventListener("pointerup",end);btn.addEventListener("pointercancel",end);btn.addEventListener("lostpointercapture",end);}
}}

$("farBtn").onclick=()=>{if(selected>=0)mutate(()=>setSelectedScalar("z",3));};$("centreBtn").onclick=()=>{if(selected>=0)mutate(()=>setSelectedScalar("z",6.5));};$("nearBtn").onclick=()=>{if(selected>=0)mutate(()=>setSelectedScalar("z",10));};
$("earthRelation").onchange=e=>{if(selected>=0)mutate(()=>pts[selected].earth=e.target.value);};$("contactState").onchange=e=>{if(selected>=0)mutate(()=>pts[selected].contact=e.target.value);};
function toggleButton(id,get,set){$(id).onclick=()=>mutate(()=>set(!get()));}
toggleButton("outlineToggle",()=>display.outline,v=>display.outline=v);toggleButton("transitionToggle",()=>showTransitions,v=>showTransitions=v);toggleButton("contactToggle",()=>showContacts,v=>showContacts=v);toggleButton("referenceCircle",()=>display.referenceCircle,v=>display.referenceCircle=v);toggleButton("mouthTailGuide",()=>display.mouthTailGuide,v=>display.mouthTailGuide=v);toggleButton("closurePreview",()=>display.closurePreview,v=>display.closurePreview=v);toggleButton("gazeArrow",()=>display.gazeArrow,v=>display.gazeArrow=v);toggleButton("arrows",()=>showArrows,v=>showArrows=v);toggleButton("points",()=>showPoints,v=>showPoints=v);toggleButton("labels",()=>showLabels,v=>showLabels=v);toggleButton("xray",()=>showXray,v=>showXray=v);toggleButton("numbers",()=>showNumbers,v=>showNumbers=v);toggleButton("lightToggle",()=>lighting.enabled,v=>lighting.enabled=v);toggleButton("shadowToggle",()=>lighting.shadows,v=>lighting.shadows=v);toggleButton("moonVisible",()=>moon.visible,v=>moon.visible=v);toggleButton("earthLock",()=>earth.locked,v=>earth.locked=v);
$("cleanMode").onclick=()=>{cleanMode=!cleanMode;if(cleanMode)diagnosticMode=false;syncAllUI();draw();};$("diagnosticMode").onclick=()=>{diagnosticMode=!diagnosticMode;if(diagnosticMode)cleanMode=false;syncAllUI();draw();};$("ghost").onclick=()=>mutate(()=>earth.alpha=earth.alpha>.5?.20:1);
$("add").onclick=()=>mutate(()=>{if(selected<0)selected=Math.max(0,pts.length-2);insertAtSource(Math.min(selected+.5,pts.length-1.001));});$("del").onclick=()=>{if(selected>0&&selected<pts.length-1&&pts.length>7)mutate(deleteSelectedPoint);};

function currentCrossings(){const list=classify(sampleCurve()).crossings||[];if(list.length)currentCrossing=clamp(currentCrossing,0,list.length-1);else currentCrossing=0;return list;}
$("cycleCrossing").onclick=()=>{const list=currentCrossings();if(!list.length)return;currentCrossing=(currentCrossing+1)%list.length;const c=list[currentCrossing];$("crossingInfo").textContent=`Crossing ${currentCrossing+1}/${list.length}: spans ${c.spanLow} & ${c.spanHigh}`;};
$("flipCrossing").onclick=()=>{const list=currentCrossings();if(!list.length)return;const c=list[currentCrossing%list.length];mutate(()=>{const v=crossingOverrides[c.key];crossingOverrides[c.key]=(v==="LOW_FRONT"||v==="A_FRONT")?"HIGH_FRONT":(v==="HIGH_FRONT"||v==="B_FRONT")?undefined:"LOW_FRONT";if(!crossingOverrides[c.key])delete crossingOverrides[c.key];});};

function setMode(next){mode=next;$("editMode").classList.toggle("active",mode==="edit");$("moveMode").classList.toggle("active",mode==="move");$("panMode").classList.toggle("active",mode==="pan");}
$("editMode").onclick=()=>setMode("edit");$("moveMode").onclick=()=>setMode("move");$("panMode").onclick=()=>setMode("pan");$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;
$("sheetHandle").onclick=()=>{$("sheet").classList.toggle("expanded");$("handleChevron").textContent=$("sheet").classList.contains("expanded")?"﹀":"︿";};$("menuBtn").onclick=()=>{$("menu").classList.toggle("open");closeContextMenu();};$("hideUI").onclick=()=>document.body.classList.add("ui-hidden");$("restoreUI").onclick=()=>document.body.classList.remove("ui-hidden");
$("openPose").onclick=()=>mutate(()=>{pts=closedPose.map(p=>({...p}));pts[0]={...pts[0],x:-1,y:2.95,z:9.5};pts[1]={...pts[1],x:-1.70,y:2.62,z:8.6};pts[2]={...pts[2],x:-2.30,y:1.90,z:7};selected=0;snakeScale=1;crossingOverrides={};biteTail=false;preserveLength=false;preserveTarget=null;});$("resetView").onclick=()=>{viewX=0;viewY=0;viewZoom=1;syncViewportUI();draw();scheduleAutosave();};$("reset").onclick=()=>mutate(()=>{pts=closedPose.map(p=>({...p}));Object.assign(endpoint,{headSize:1,headRotation:0,neckWidth:1,eyeOpen:.35,eyeX:.22,eyeY:-.18,gazeDirection:-70,mouthOpen:.18,tailLength:1,tailWidth:1,tailDirection:0,tailCurvature:0});Object.assign(earth,{x:0,y:0,r:2.50,depth:6.5,scale:1,alpha:1,locked:true});Object.assign(moon,{visible:true,angle:35,radius:3,size:.27,relativeDepth:1});Object.assign(lighting,{enabled:true,direction:-45,intensity:.65,softness:.6,shadows:true,depthFog:.16});Object.assign(display,{outline:true,outlineThickness:.08,referenceCircle:false,mouthTailGuide:false,closurePreview:false,gazeArrow:true,gazeOpacity:.95,gazeStars:true});snakeScale=1;perspectiveStrength=1;crossingOverrides={};biteTail=true;preserveLength=false;preserveTarget=null;enforceBiteVisual(null);selected=-1;});

let contextTarget=null;
function closeContextMenu(){$("contextMenu").classList.remove("open");contextTarget=null;}
function cycleEarthRelation(v){return v==="AUTO"?"FRONT_OF_EARTH":v==="FRONT_OF_EARTH"?"BEHIND_EARTH":"AUTO";}
function cycleContact(v){return v==="AUTO"?"FREE":v==="FREE"?"TOUCHING_EARTH":"AUTO";}
function openContextMenu(target,x,y){contextTarget=target;const point=target?.type==="point",curve=target?.type==="curve",earthTarget=target?.type==="earth";$("contextAdd").classList.toggle("hidden",!curve);$("contextDuplicate").classList.toggle("hidden",!point);$("contextDelete").classList.toggle("hidden",!point);$("contextEarthRelation").classList.toggle("hidden",!point);$("contextContact").classList.toggle("hidden",!point);$("contextEarthLock").classList.toggle("hidden",!earthTarget);if(point){selected=target.index;const p=pts[selected];$("contextDelete").disabled=selected===0||selected===pts.length-1||pts.length<=7;$("contextEarthRelation").textContent=`Earth: ${p.earth==="FRONT_OF_EARTH"?"FRONT":p.earth==="BEHIND_EARTH"?"BEHIND":"AUTO"}`;$("contextContact").textContent=`Contact: ${p.contact.replace("TOUCHING_EARTH","TOUCHING")}`;syncAllUI();draw();}if(earthTarget)$("contextEarthLock").textContent=earth.locked?"Unlock Earth":"Lock Earth";const menu=$("contextMenu");menu.classList.add("open");const mw=176,mh=220;menu.style.left=clamp(x+6,6,W-mw-6)+"px";menu.style.top=clamp(y+6,6,H-Math.min(mh,H-12)-6)+"px";}
$("contextAdd").onclick=()=>{const target=contextTarget;if(target?.type==="curve")mutate(()=>insertPointAtLocation(target.loc));closeContextMenu();};$("contextDuplicate").onclick=()=>{if(contextTarget?.type==="point")mutate(duplicateSelectedPoint);closeContextMenu();};$("contextDelete").onclick=()=>{if(contextTarget?.type==="point"&&selected>0&&selected<pts.length-1&&pts.length>7)mutate(deleteSelectedPoint);closeContextMenu();};$("contextEarthRelation").onclick=()=>{if(contextTarget?.type==="point"&&selected>=0)mutate(()=>pts[selected].earth=cycleEarthRelation(pts[selected].earth));closeContextMenu();};$("contextContact").onclick=()=>{if(contextTarget?.type==="point"&&selected>=0)mutate(()=>pts[selected].contact=cycleContact(pts[selected].contact));closeContextMenu();};$("contextEarthLock").onclick=()=>{mutate(()=>earth.locked=!earth.locked);closeContextMenu();};
function contextHit(x,y){const p=nearestPoint(x,y);if(p>=0)return{type:"point",index:p};const loc=nearestCurveLocation(x,y);if(loc)return{type:"curve",loc};if(hitEarth(x,y))return{type:"earth"};return null;}

const pointers=new Map();
let dragState=null,gesture=null,longPressTimer=0,longPressOrigin=null;
function cancelLongPress(){clearTimeout(longPressTimer);longPressTimer=0;longPressOrigin=null;}
function scheduleLongPress(target,x,y,pointerId){cancelLongPress();if(!target)return;longPressOrigin={x,y,pointerId,target};longPressTimer=setTimeout(()=>{const o=longPressOrigin;if(!o||!pointers.has(pointerId))return;if(o.target.type==="curve"){mutate(()=>insertPointAtLocation(o.target.loc));dragState={kind:"context",pointerId};}else{const before=dragState?.pointerId===pointerId?dragState.before:null;openContextMenu(o.target,x,y);dragState={kind:"context",pointerId,before};}cancelLongPress();},500);}
function pointerPos(e){return{x:e.clientX,y:e.clientY};}
function beginGesture(){cancelLongPress();if(dragState?.before)commit(dragState.before);dragState=null;const arr=[...pointers.values()];if(arr.length<2)return;const a=arr[0],b=arr[1],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},dist=Math.hypot(a.x-b.x,a.y-b.y)||1;gesture={startZoom:viewZoom,startDist:dist,worldX:(mid.x-cx-viewX)/(baseScale*viewZoom),worldY:-(mid.y-cy-viewY)/(baseScale*viewZoom)};}
function updateGesture(){if(!gesture||pointers.size<2)return;const arr=[...pointers.values()],a=arr[0],b=arr[1],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},dist=Math.hypot(a.x-b.x,a.y-b.y)||1;viewZoom=clamp(gesture.startZoom*dist/gesture.startDist,.35,4);viewX=mid.x-cx-gesture.worldX*baseScale*viewZoom;viewY=mid.y-cy+gesture.worldY*baseScale*viewZoom;syncViewportUI();draw();}
function finishDrag(){cancelLongPress();if(dragState?.before)commit(dragState.before);dragState=null;syncAllUI();}
function collapseControls(){const sheet=$("sheet");if(!document.body.classList.contains("panel-floating")&&sheet){sheet.classList.remove("expanded");sheet.style.height="";$("handleChevron").textContent="︿";}dispatchEvent(new CustomEvent("ouroboros:collapse-sheet"));}
canvas.addEventListener("pointerdown",e=>{if(e.button===2)return;closeContextMenu();$("menu").classList.remove("open");canvas.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{...pointerPos(e),pointerType:e.pointerType});if(pointers.size===2){beginGesture();e.preventDefault();return;}if(pointers.size>2){e.preventDefault();return;}const{x,y}=pointerPos(e),forcePan=e.button===1||spaceHeld;if(forcePan){dragState={kind:"pan",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y};e.preventDefault();return;}if(e.button!==0){e.preventDefault();return;}const point=nearestPoint(x,y),earthHit=hitEarth(x,y),curve=nearestCurveLocation(x,y),target=point>=0?{type:"point",index:point}:(!earth.locked&&earthHit)?{type:"earth"}:curve?{type:"curve",loc:curve}:earthHit?{type:"earth"}:null;if(mode==="edit"){if(point>=0){selected=point;dragState={kind:"point",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y,before:sceneState()};syncAllUI();draw();scheduleLongPress(target,x,y,e.pointerId);}else if(!earth.locked&&earthHit){dragState={kind:"earth",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y,before:sceneState()};scheduleLongPress({type:"earth"},x,y,e.pointerId);}else{dragState={kind:"pending",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y,target};scheduleLongPress(target,x,y,e.pointerId);}}else if(mode==="move")dragState={kind:"snake",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y,before:sceneState()};else dragState={kind:"pan",pointerId:e.pointerId,lastX:x,lastY:y,startX:x,startY:y};e.preventDefault();});
canvas.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;const{x,y}=pointerPos(e);pointers.set(e.pointerId,{x,y,pointerType:e.pointerType});if(pointers.size>=2){updateGesture();e.preventDefault();return;}if(!dragState||dragState.pointerId!==e.pointerId)return;const dx=x-dragState.lastX,dy=y-dragState.lastY,total=Math.hypot(x-(dragState.startX??x),y-(dragState.startY??y));if(total>9)cancelLongPress();dragState.lastX=x;dragState.lastY=y;const s=currentScale(),wx=dx/s,wy=-dy/s;if(dragState.kind==="point"&&selected>=0)movePoint(selected,wx,wy);else if(dragState.kind==="snake")for(const p of pts){p.x+=wx;p.y+=wy;}else if(dragState.kind==="earth"){earth.x+=wx;earth.y+=wy;}else if(dragState.kind==="pan"){viewX+=dx;viewY+=dy;}else return;syncAllUI();draw();e.preventDefault();});
function endPointer(e){pointers.delete(e.pointerId);if(gesture){if(pointers.size<2){gesture=null;dragState=null;scheduleAutosave();}e.preventDefault();return;}if(dragState?.pointerId===e.pointerId){if(dragState.kind==="pending"){const moved=Math.hypot((dragState.lastX??dragState.startX)-(dragState.startX??0),(dragState.lastY??dragState.startY)-(dragState.startY??0));cancelLongPress();if(!dragState.target&&moved<=9){selected=-1;collapseControls();syncAllUI();draw();}}finishDrag();}cancelLongPress();e.preventDefault();}
canvas.addEventListener("pointerup",endPointer);canvas.addEventListener("pointercancel",endPointer);
canvas.addEventListener("contextmenu",e=>{e.preventDefault();const target=contextHit(e.clientX,e.clientY);if(target)openContextMenu(target,e.clientX,e.clientY);else closeContextMenu();});
canvas.addEventListener("dblclick",e=>{if(mode!=="edit")return;if(nearestPoint(e.clientX,e.clientY)>=0)return;const loc=nearestCurveLocation(e.clientX,e.clientY);if(loc)mutate(()=>insertPointAtLocation(loc));});
canvas.addEventListener("wheel",e=>{e.preventDefault();closeContextMenu();if(e.shiftKey){const pan=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY;viewX-=pan;draw();scheduleAutosave();return;}const factor=Math.exp(-e.deltaY*.0015);zoomAt(e.clientX,e.clientY,viewZoom*factor);},{passive:false});

function formFocused(){const a=document.activeElement;return !!a&&(a.tagName==="INPUT"||a.tagName==="TEXTAREA"||a.tagName==="SELECT"||a.isContentEditable);}
let keyNudgeBefore=null;
function finishKeyNudge(){if(!keyNudgeBefore)return;commit(keyNudgeBefore);keyNudgeBefore=null;syncAllUI();}
addEventListener("keydown",e=>{if(formFocused())return;const key=e.key.toLowerCase(),mod=e.metaKey||e.ctrlKey;if(mod&&key==="z"){e.preventDefault();finishKeyNudge();if(e.shiftKey)redo();else undo();return;}if(mod&&key==="y"){e.preventDefault();finishKeyNudge();redo();return;}if(e.key===" "){spaceHeld=true;e.preventDefault();return;}if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)&&selected>=0){e.preventDefault();if(!keyNudgeBefore)keyNudgeBefore=sceneState();const step=e.shiftKey?.10:.02;if(e.key==="ArrowLeft")movePoint(selected,-step,0);else if(e.key==="ArrowRight")movePoint(selected,step,0);else if(e.key==="ArrowUp")movePoint(selected,0,step);else movePoint(selected,0,-step);syncAllUI();draw();return;}if(key==="e"){finishKeyNudge();setMode("edit");return;}if(key==="m"){finishKeyNudge();setMode("move");return;}if(key==="p"){finishKeyNudge();setMode("pan");return;}if(e.key==="Delete"||e.key==="Backspace"){finishKeyNudge();if(selected>0&&selected<pts.length-1&&pts.length>7){e.preventDefault();mutate(deleteSelectedPoint);}return;}if(e.key==="+"||e.key==="="){finishKeyNudge();e.preventDefault();zoomAt(W/2,H/2,viewZoom*1.12);return;}if(e.key==="-"||e.key==="_"){finishKeyNudge();e.preventDefault();zoomAt(W/2,H/2,viewZoom/1.12);return;}if(e.key==="Escape"){finishKeyNudge();closeContextMenu();$("menu").classList.remove("open");$("overlay").style.display="none";}});
addEventListener("keyup",e=>{if(e.key===" ")spaceHeld=false;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key))finishKeyNudge();});
function cancelActiveInput(){finishKeyNudge();cancelLongPress();if(dragState?.before)commit(dragState.before);pointers.clear();dragState=null;gesture=null;spaceHeld=false;syncAllUI();}
addEventListener("blur",cancelActiveInput);
document.addEventListener("visibilitychange",()=>{if(document.hidden)cancelActiveInput();syncSparkleAnimation();});

const headKeys=["headSize","headRotation","neckWidth","eyeOpen","eyeX","eyeY","gazeDirection","mouthOpen"],tailKeys=["tailLength","tailWidth","tailDirection","tailCurvature"];
function pickEndpoint(keys){const out={};for(const key of keys)out[key]=endpoint[key];return out;}
function exportState(includeCheckpoints=true){return{version:9,coordinateSystem:{depthMinimum:0,depthNormal:6.5,depthMaximum:14,direction:"tail-to-head"},perspectiveStrength,earth:clone(earth),moon:clone(moon),snake:{scale:snakeScale,points:clone(pts),head:pickEndpoint(headKeys),tail:pickEndpoint(tailKeys)},constraints:{biteTail,preserveLength,preserveTarget},topology:{crossingOverrides:clone(crossingOverrides)},lighting:clone(lighting),view:{x:viewX,y:viewY,zoom:viewZoom},display:{outline:display.outline,outlineThickness:display.outlineThickness,referenceCircle:display.referenceCircle,mouthTailGuide:display.mouthTailGuide,closurePreview:display.closurePreview,gazeArrow:display.gazeArrow,gazeOpacity:display.gazeOpacity,gazeStars:display.gazeStars,arrows:showArrows,points:showPoints,depthLabels:showLabels,xray:showXray,numbers:showNumbers,transitions:showTransitions,contacts:showContacts,diagnosticMode,cleanMode},checkpoints:includeCheckpoints?clone(checkpoints):{}};}
function inferLegacyBite(){if(pts.length<2)return true;const{mouth,tip}=biteAnchorsWorld();return Math.hypot(mouth.x-tip.x,mouth.y-tip.y)<=Math.max(.50,.32*snakeScale);}
function importData(data,silent=false){if(data.version===4&&data.snake?.head){pts=[data.snake.head.point,...(data.snake.body||[]),data.snake.tail.point].map(makePoint);snakeScale=+(data.snake.scale??1);endpoint.headSize=+(data.snake.head.size??1);endpoint.tailLength=+(data.snake.tail.length??1);endpoint.tailWidth=+(data.snake.tail.width??1);if(data.earth){earth.x=+(data.earth.x??0);earth.y=+(data.earth.y??0);earth.r=+(data.earth.radius??2.15);}if(data.view){viewX=+(data.view.x??0);viewY=+(data.view.y??0);viewZoom=+(data.view.zoom??1);}}else{const rawPts=data.snake?.points||data.pts;if(rawPts)pts=rawPts.map(p=>Array.isArray(p)?makePoint([p[0],p[1],(+p[2]||6.5)-6.5]):{x:+p.x,y:+p.y,z:clamp(+p.z,0,14),width:+(p.width??1),earth:p.earth||"AUTO",contact:p.contact||"AUTO"});snakeScale=+(data.snake?.scale??data.snakeScale??1);perspectiveStrength=+(data.perspectiveStrength??1);Object.assign(endpoint,data.snake?.head||data.endpoint||{});Object.assign(endpoint,data.snake?.tail||{});Object.assign(earth,data.earth||{});Object.assign(moon,data.moon||{});Object.assign(lighting,data.lighting||{});crossingOverrides=clone(data.topology?.crossingOverrides||data.crossingOverrides||{});if(data.display){for(const key of["outline","outlineThickness","referenceCircle","mouthTailGuide","closurePreview","gazeArrow","gazeOpacity","gazeStars"])if(key in data.display)display[key]=data.display[key];showArrows=data.display.arrows??showArrows;showPoints=data.display.points??showPoints;showLabels=data.display.depthLabels??showLabels;showXray=data.display.xray??showXray;showNumbers=data.display.numbers??showNumbers;showTransitions=data.display.transitions??showTransitions;showContacts=data.display.contacts??showContacts;diagnosticMode=data.display.diagnosticMode??diagnosticMode;cleanMode=data.display.cleanMode??cleanMode;}if(data.view){viewX=+(data.view.x??0);viewY=+(data.view.y??0);viewZoom=clamp(+(data.view.zoom??1),.35,4);}if(data.checkpoints){for(const k of Object.keys(checkpoints))delete checkpoints[k];Object.assign(checkpoints,clone(data.checkpoints));}}
if(data.constraints){biteTail=data.constraints.biteTail??true;preserveLength=!!data.constraints.preserveLength;preserveTarget=Number.isFinite(+data.constraints.preserveTarget)?+data.constraints.preserveTarget:null;}else{biteTail=inferLegacyBite();preserveLength=false;preserveTarget=null;}if(biteTail)enforceBiteVisual(null);if(preserveLength&&!Number.isFinite(preserveTarget))preserveTarget=arcLength();selected=-1;if(!silent){syncAllUI();draw();autosave();syncSparkleAnimation();}}

function openJSON(kind){$("overlay").style.display="flex";$("snapshotImage").style.display="none";$("checkpointBox").style.display="none";$("jsonBox").style.display="block";$("overlayTitle").textContent=kind==="import"?"Paste pose JSON":"Exported pose JSON";$("jsonBox").value=kind==="import"?"":JSON.stringify(exportState(),null,2);$("applyImport").style.display=kind==="import"?"block":"none";$("copyOverlay").style.display="block";}
$("export").onclick=()=>openJSON("export");$("import").onclick=()=>openJSON("import");$("copyOverlay").onclick=async()=>{try{await navigator.clipboard.writeText($("jsonBox").value);}catch(err){$("jsonBox").focus();$("jsonBox").select();document.execCommand("copy");}};$("applyImport").onclick=()=>{try{const before=sceneState();importData(JSON.parse($("jsonBox").value));commit(before);$("overlay").style.display="none";}catch(err){alert("Could not import that JSON.");}};
function snapshot(kind){const old={cleanMode,diagnosticMode,showPoints,showLabels};if(kind==="clean"){cleanMode=true;diagnosticMode=false;showPoints=false;showLabels=false;}else if(kind==="diagnostic"){cleanMode=false;diagnosticMode=true;showPoints=true;showLabels=true;}else{showPoints=false;showLabels=false;}draw();const image=canvas.toDataURL("image/png");({cleanMode,diagnosticMode,showPoints,showLabels}=old);draw();$("overlay").style.display="flex";$("overlayTitle").textContent=kind==="clean"?"Clean Snapshot":kind==="diagnostic"?"Diagnostic Snapshot":"Snapshot";$("snapshotImage").src=image;$("snapshotImage").style.display="block";$("jsonBox").style.display="none";$("checkpointBox").style.display="none";$("copyOverlay").style.display="none";$("applyImport").style.display="none";}
$("snapshot").onclick=()=>snapshot("normal");$("cleanSnapshot").onclick=()=>snapshot("clean");$("diagSnapshot").onclick=()=>snapshot("diagnostic");
function saveCheckpoint(){const name=prompt("Checkpoint name","final");if(!name)return;checkpoints[name]=sceneState();autosave();}$("saveCheckpoint").onclick=saveCheckpoint;
function showCheckpoints(){$("overlay").style.display="flex";$("overlayTitle").textContent="Checkpoints";$("snapshotImage").style.display="none";$("jsonBox").style.display="none";$("checkpointBox").style.display="block";$("copyOverlay").style.display="none";$("applyImport").style.display="none";const box=$("checkpointBox");box.className="";box.innerHTML="";const names=Object.keys(checkpoints);if(!names.length){box.textContent="No checkpoints saved.";return;}for(const name of names){const row=document.createElement("div");row.className="checkpointRow";const label=document.createElement("span");label.textContent=name;const load=document.createElement("button");load.textContent="Load";load.onclick=()=>{const before=sceneState();applyScene(checkpoints[name]);commit(before);$("overlay").style.display="none";};const del=document.createElement("button");del.textContent="Delete";del.onclick=()=>{delete checkpoints[name];autosave();showCheckpoints();};row.append(label,load,del);box.appendChild(row);}}
$("checkpointMenu").onclick=showCheckpoints;
function showGestureHelp(){$("overlay").style.display="flex";$("overlayTitle").textContent="Controls & gestures";$("snapshotImage").style.display="none";$("jsonBox").style.display="none";$("checkpointBox").style.display="block";$("copyOverlay").style.display="none";$("applyImport").style.display="none";const box=$("checkpointBox");box.className="helpText";box.innerHTML=`<p><b>Edit:</b> tap/click a point to select; drag it to pose. Tap unobstructed sky to clear selection and collapse the docked controls. Long-press a snake segment or double-click it to add a point. Long-press/right-click a point for point actions.</p><p><b>Move:</b> drag to move only the snake. <b>Pan:</b> drag to move only the viewport. When Earth is unlocked, drag Earth in Edit mode to move Earth and Moon.</p><p><b>Touch:</b> two fingers pan and pinch-zoom at the same time. <b>Mouse/trackpad:</b> wheel zooms around the pointer; Shift+wheel pans; middle-drag or Space+drag temporarily pans.</p><p><b>Ouroboros:</b> Bite tail closes/links the endpoints. Release tail frees them. Preserve length applies only to HEAD/TAIL dragging and uses bounded local correction.</p><p><b>Keyboard:</b> E Edit, M Move, P Pan, arrow keys nudge the selected point (Shift = larger step), Cmd/Ctrl+Z Undo, Cmd/Ctrl+Shift+Z or Cmd/Ctrl+Y Redo, Delete/Backspace removes an eligible body point, +/- zoom, Esc closes menus.</p><p><b>Numbers:</b> X, Y and every slider have − / + and an exact-value field. Hold − or + to repeat.</p>`;}
$("gestureHelp").onclick=showGestureHelp;$("closeOverlay").onclick=()=>$("overlay").style.display="none";

addEventListener("resize",resize);
installTaskControls();
enhanceNumericControls();
restoreAutosave();
if(biteTail)enforceBiteVisual(null);
syncAllUI();
resize();
syncSparkleAnimation();
})();